# Copyright 2022-present, Lorenzo Bonicelli, Pietro Buzzega, Matteo Boschini, Angelo Porrello, Simone Calderara.
# All rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

best_args = {
     'seq-cifar10': {
        'er': {200: {'lr': 0.1,
                     'minibatch_size': 10,
                     'batch_size': 10,
                     'n_epochs': 1},
               500: {'lr': 0.1,
                     'minibatch_size': 10,
                     'batch_size': 10,
                     'n_epochs': 1},
               1000: {'lr': 0.1,
                      'minibatch_size': 10,
                      'batch_size': 10,
                      'n_epochs': 1}},
        'gss': {200: {'lr': 0.03,
                      'minibatch_size': 10,
                      'gss_minibatch_size': 10,
                      'batch_size': 10,
                      'n_epochs': 1,
                      'batch_num': 1},
                500: {'lr': 0.03,
                      'minibatch_size': 10,
                      'gss_minibatch_size': 10,
                      'batch_size': 10,
                      'n_epochs': 1,
                      'batch_num': 1},
                1000: {'lr': 0.03,
                       'minibatch_size': 10,
                       'gss_minibatch_size': 10,
                       'batch_size': 10,
                       'n_epochs': 1,
                       'batch_num': 1}},
        'quadaug': {200: {'lr': 0.01,
                       'minibatch_size': 10,
                       'eta': 0.3,
                       'lam': 0.25,
                       'er_alpha': 3.0,
                       'er_beta': 3.0,
                       'sscci_alpha': 3.0,
                       'crc_alpha': 1.0,
                       'csd_alpha': 1.0,
                       'batch_size': 10,
                       'n_epochs': 1},
                 500: {'lr': 0.01,
                       'minibatch_size': 10,
                       'eta': 0.3,
                       'lam': 0.25,
                       'er_alpha': 3.0,
                       'er_beta': 3.0,
                       'sscci_alpha': 3.0,
                       'crc_alpha': 1.0,
                       'csd_alpha': 1.0,
                       'batch_size': 10,
                       'n_epochs': 1},
                 1000: {'lr': 0.01,
                        'minibatch_size': 10,
                        'eta': 0.3,
                        'lam': 0.25,
                        'er_alpha': 3.0,
                        'er_beta': 3.0,
                        'sscci_alpha': 3.0,
                        'crc_alpha': 1.0,
                        'csd_alpha': 1.0,
                        'batch_size': 10,
                        'n_epochs': 1}},
        'derpp': {200: {'lr': 0.03,
                        'minibatch_size': 10,
                        'alpha': 0.2,
                        'beta': 0.5,
                        'batch_size': 10,
                        'n_epochs': 1},
                  500: {'lr': 0.03,
                        'minibatch_size': 10,
                        'alpha': 0.2,
                        'beta': 0.5,
                        'batch_size': 10,
                        'n_epochs': 1},
                  1000: {'lr': 0.03,
                         'minibatch_size': 10,
                         'alpha': 0.2,
                         'beta': 0.5,
                         'batch_size': 10,
                         'n_epochs': 1}},
    },
'seq-cifar100': {
    'quadaug': {200: {'lr': 0.01,
                   'minibatch_size': 10,
                   'eta': 0.3,
                   'lam': 0.25,
                   'er_alpha': 3.0,
                   'er_beta': 3.0,
                   'sscci_alpha': 3.0,
                   'crc_alpha': 1.0,
                   'csd_alpha': 1.0,
                   'batch_size': 10,
                   'n_epochs': 1},
             500: {'lr': 0.01,
                   'minibatch_size': 10,
                   'eta': 0.3,
                   'lam': 0.25,
                   'er_alpha': 3.0,
                   'er_beta': 3.0,
                   'sscci_alpha': 3.0,
                   'crc_alpha': 1.0,
                   'csd_alpha': 1.0,
                   'batch_size': 10,
                   'n_epochs': 1},
             1000: {'lr': 0.01,
                    'minibatch_size': 10,
                    'eta': 0.3,
                    'lam': 0.25,
                    'er_alpha': 3.0,
                    'er_beta': 3.0,
                    'sscci_alpha': 3.0,
                    'crc_alpha': 1.0,
                    'csd_alpha': 1.0,
                    'batch_size': 10,
                    'n_epochs': 1}},
    },
'seq-cifar10-blurry': {
'gss': {200: {'lr': 0.03,
                                  'minibatch_size': 10,
                                  'gss_minibatch_size': 10,
                                  'batch_size': 10,
                                  'n_epochs': 1,
                                  'batch_num': 1},
                            500: {'lr': 0.03,
                                  'minibatch_size': 10,
                                  'gss_minibatch_size': 10,
                                  'batch_size': 10,
                                  'n_epochs': 1,
                                  'batch_num': 1},
                            1000: {'lr': 0.03,
                                   'minibatch_size': 10,
                                   'gss_minibatch_size': 10,
                                   'batch_size': 10,
                                   'n_epochs': 1,
                                   'batch_num': 1}},
        'quadaug': {200: {'lr': 0.01,
                       'minibatch_size': 10,
                       'eta': 0.3,
                       'lam': 0.25,
                       'er_alpha': 3.0,
                       'er_beta': 3.0,
                       'sscci_alpha': 3.0,
                       'crc_alpha': 1.0,
                       'csd_alpha': 1.0,
                       'batch_size': 10,
                       'n_epochs': 1},
                 500: {'lr': 0.01,
                       'minibatch_size': 10,
                       'eta': 0.3,
                       'lam': 0.25,
                       'er_alpha': 3.0,
                       'er_beta': 3.0,
                       'sscci_alpha': 3.0,
                       'crc_alpha': 1.0,
                       'csd_alpha': 1.0,
                       'batch_size': 10,
                       'n_epochs': 1},
                 1000: {'lr': 0.01,
                        'minibatch_size': 10,
                        'eta': 0.3,
                        'lam': 0.25,
                        'er_alpha': 3.0,
                        'er_beta': 3.0,
                        'sscci_alpha': 3.0,
                        'crc_alpha': 1.0,
                        'csd_alpha': 1.0,
                        'batch_size': 10,
                        'n_epochs': 1}},
        'der': {200: {'lr': 0.03,
                                  'minibatch_size': 10,
                                  'alpha': 0.3,
                                  'batch_size': 10,
                                  'n_epochs': 1},
                            500: {'lr': 0.03,
                                  'minibatch_size': 10,
                                  'alpha': 0.3,
                                  'batch_size': 10,
                                  'n_epochs': 1},
                            1000: {'lr': 0.03,
                                   'minibatch_size': 10,
                                   'alpha': 0.3,
                                   'batch_size': 10,
                                   'n_epochs': 1}},
        'derpp': {200: {'lr': 0.03,
                        'minibatch_size': 10,
                        'alpha': 0.2,
                        'beta': 0.5,
                        'batch_size': 10,
                        'n_epochs': 1},
                  500: {'lr': 0.03,
                        'minibatch_size': 10,
                        'alpha': 0.2,
                        'beta': 0.5,
                        'batch_size': 10,
                        'n_epochs': 1},
                  1000: {'lr': 0.03,
                         'minibatch_size': 10,
                         'alpha': 0.2,
                         'beta': 0.5,
                         'batch_size': 10,
                         'n_epochs': 1}},
'clser': {
                        200: {
                            'reg_weight': 0.15,
                            'stable_model_update_freq': 0.1,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 0.3,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.1,
                            'minibatch_size': 10,
                            'batch_size': 10,
                            'n_epochs': 1,
                        },
                        500: {
                            'reg_weight': 0.15,
                            'stable_model_update_freq': 0.1,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 0.9,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.1,
                            'minibatch_size': 10,
                            'batch_size': 10,
                            'n_epochs': 1,
                        },
                        1000: {
                            'reg_weight': 0.15,
                            'stable_model_update_freq': 0.8,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 1.0,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.03,
                            'minibatch_size': 10,
                            'batch_size': 10,
                            'n_epochs': 1,
                        }},
        'coca': {200: {'lr': 0.03,
                       'minibatch_size': 10,
                       'alpha': 0.1,
                       'beta': 0.5,
                       'batch_size': 10,
                       'n_epochs': 1},
                 500: {'lr': 0.03,
                       'minibatch_size': 10,
                       'alpha': 0.2,
                       'beta': 0.5,
                       'batch_size': 10,
                       'n_epochs': 1},
                 1000: {'lr': 0.03,
                        'minibatch_size': 10,
                        'alpha': 0.1,
                        'beta': 1.0,
                        'batch_size': 10,
                        'n_epochs': 1}},
        'ocdnet': {
            200: {
                'Bernoulli_probability': 0.2,
                'ER_weight': 0.5,
                'lr': 0.1,
                'minibatch_size': 10,
                'batch_size': 10,
                'n_epochs': 1,
            },
            500: {
                'Bernoulli_probability': 0.2,
                'ER_weight': 0.5,
                'lr': 0.1,
                'minibatch_size': 10,
                'batch_size': 10,
                'n_epochs': 1,
            },
            1000: {
                'Bernoulli_probability': 0.8,
                'ER_weight': 1.0,
                'lr': 0.1,
                'minibatch_size': 10,
                'batch_size': 10,
                'n_epochs': 1, }}
    },
'mnist-360': {
'gss': {200: {'lr': 0.03,
                                  'minibatch_size': 10,
                                  'gss_minibatch_size': 10,
                                  'batch_size': 10,
                                  'n_epochs': 1,
                                  'batch_num': 1},
                            500: {'lr': 0.03,
                                  'minibatch_size': 10,
                                  'gss_minibatch_size': 10,
                                  'batch_size': 10,
                                  'n_epochs': 1,
                                  'batch_num': 1},
                            1000: {'lr': 0.03,
                                   'minibatch_size': 10,
                                   'gss_minibatch_size': 10,
                                   'batch_size': 10,
                                   'n_epochs': 1,
                                   'batch_num': 1}},
        'quadaug': {200: {'lr': 0.03,
                       'minibatch_size': 10,
                       'eta': 0.2,
                       'lam': 0.25,
                       'er_alpha': 0.1,
                       'er_beta': 0.1,
                       'sscci_alpha': 0.5,
                       'crc_alpha': 1.0,
                       'csd_alpha': 0.5,
                       'batch_size': 10,
                       'n_epochs': 1},
                 500: {'lr': 0.03,
                       'minibatch_size': 10,
                       'eta': 0.2,
                       'lam': 0.25,
                       'er_alpha': 0.1,
                       'er_beta': 0.1,
                       'sscci_alpha': 0.5,
                       'crc_alpha': 1.0,
                       'csd_alpha': 0.5,
                       'batch_size': 10,
                       'n_epochs': 1},
                 1000: {'lr': 0.03,
                       'minibatch_size': 10,
                       'eta': 0.2,
                       'lam': 0.25,
                       'er_alpha': 0.1,
                       'er_beta': 0.1,
                       'sscci_alpha': 0.5,
                       'crc_alpha': 1.0,
                       'csd_alpha': 0.5,
                       'batch_size': 10,
                       'n_epochs': 1}},
        'der': {100: {'lr': 0.03,
                      'batch_size': 10,
                      'minibatch_size': 10,
                      'alpha': 0.5},
                500: {'lr': 0.03,
                      'batch_size': 10,
                      'minibatch_size': 10,
                      'alpha': 0.5},
                1000: {'lr': 0.03,
                       'batch_size': 10,
                       'minibatch_size': 10,
                       'alpha': 0.5}},
        'derpp': {200: {'lr': 0.03,
                        'minibatch_size': 10,
                        'alpha': 0.5,
                        'beta': 1.0,
                        'batch_size': 10,
                        'n_epochs': 1},
                  500: {'lr': 0.03,
                        'minibatch_size': 10,
                        'alpha': 0.5,
                        'beta': 1.0,
                        'batch_size': 10,
                        'n_epochs': 1},
                  1000: {'lr': 0.03,
                         'minibatch_size': 10,
                         'alpha': 0.2,
                         'beta': 1.0,
                         'batch_size': 10,
                         'n_epochs': 1}},
        'clser': {
                        200: {
                            'reg_weight': 0.15,
                            'stable_model_update_freq': 0.1,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 0.3,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.03,
                            'minibatch_size': 10,
                            'batch_size': 10,
                            'n_epochs': 1,
                        },
                        500: {
                            'reg_weight': 0.15,
                            'stable_model_update_freq': 0.1,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 0.9,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.03,
                            'minibatch_size': 10,
                            'batch_size': 10,
                            'n_epochs': 1,
                        },
                        1000: {
                            'reg_weight': 0.15,
                            'stable_model_update_freq': 0.8,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 1.0,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.03,
                            'minibatch_size': 10,
                            'batch_size': 10,
                            'n_epochs': 1,
                        }},
        'coca': {200: {'lr': 0.03,
                       'minibatch_size': 10,
                       'alpha': 0.1,
                       'beta': 0.5,
                       'batch_size': 10,
                       'n_epochs': 1},
                 500: {'lr': 0.03,
                       'minibatch_size': 10,
                       'alpha': 0.2,
                       'beta': 0.5,
                       'batch_size': 10,
                       'n_epochs': 1},
                 1000: {'lr': 0.03,
                        'minibatch_size': 10,
                        'alpha': 0.1,
                        'beta': 1.0,
                        'batch_size': 10,
                        'n_epochs': 1}},
        'ocdnet': {
            100: {
                'Bernoulli_probability': 0.2,
                'ER_weight': 0.5,
                'lr': 0.03,
                'minibatch_size': 10,
                'batch_size': 10,
                'n_epochs': 1,
            },
            500: {
                'Bernoulli_probability': 0.2,
                'ER_weight': 0.5,
                'lr': 0.03,
                'minibatch_size': 10,
                'batch_size': 10,
                'n_epochs': 1,
            },
            1000: {
                'Bernoulli_probability': 0.8,
                'ER_weight': 1.0,
                'lr': 0.03,
                'minibatch_size': 10,
                'batch_size': 10,
                'n_epochs': 1, }}
    },
'seq-miniimg': {
    'quadaug': {1000: {'lr': 0.01,
                   'minibatch_size': 10,
                   'eta': 0.3,
                   'lam': 0.25,
                   'er_alpha': 3.0,
                   'er_beta': 3.0,
                   'sscci_alpha': 3.0,
                   'crc_alpha': 1.0,
                   'csd_alpha': 1.0,
                   'batch_size': 10,
                   'n_epochs': 1},
             2000: {'lr': 0.01,
                   'minibatch_size': 10,
                   'eta': 0.3,
                   'lam': 0.25,
                   'er_alpha': 3.0,
                   'er_beta': 3.0,
                   'sscci_alpha': 3.0,
                   'crc_alpha': 1.0,
                   'csd_alpha': 1.0,
                   'batch_size': 10,
                   'n_epochs': 1},
             500: {'lr': 0.01,
                    'minibatch_size': 10,
                    'eta': 0.3,
                    'lam': 0.25,
                    'er_alpha': 3.0,
                    'er_beta': 3.0,
                    'sscci_alpha': 3.0,
                    'crc_alpha': 1.0,
                    'csd_alpha': 1.0,
                    'batch_size': 10,
                    'n_epochs': 1}},
    'derpp': {1000: {'lr': 0.01,
                     'minibatch_size': 10,
                     'alpha': 0.1,
                     'beta': 1.0,
                     'batch_size': 10,
                     'n_epochs': 1},
              2000: {'lr': 0.01,
                     'minibatch_size': 10,
                     'alpha': 0.1,
                     'beta': 1.0,
                     'batch_size': 10,
                     'n_epochs': 1},
              4000: {'lr': 0.01,
                     'minibatch_size': 10,
                     'alpha': 0.1,
                     'beta': 1.0,
                     'batch_size': 10,
                     'n_epochs': 1}}
    },

}
